POST http://localhost:8080/api/orders
Content-Type: application/json

	{"persons":1,"orderItems":[{"itemId":1,"area":"Drink","quantity":2,"orderId":"192911160d2342","isCompleted":false},{"itemId":6,"area":"Waffle","quantity":3,"orderId":"192911160d2389","isCompleted":false},{"itemId":12,"area":"Consomme_Soup","quantity":1,"orderId":"192911160d227c","isCompleted":false}],"total":0,"payment":"cash","submitId":"postFromGAS","tableNum":2,"isServed":false,"isEatIn":true}



###

GET http://localhost:8080/api/orders/orderitems/Drinks

###

PATCH http://localhost:8080/api/orders/orderitems/18f29d2bb9ae1/18f29d2891b36c

###

GET http://localhost:8080/api/orders/orders

###
PATCH http://localhost:8080/api/orders/18f2ff07d902bd

###
GET http://localhost:8080/api/orders/receipt/18f2ff07d902bd

###
GET http://localhost:8080/api/orders/info

###
PATCH http://localhost:8080/api/status/
Content-Type: application/json

{
    "id":1,
    "status":1
}


###
POST https://script.google.com/macros/s/AKfycbxItAYZ6vyT9Nn_YcTBMvyeQA2qWRL0YQNF8NvCuq2x4NKJh5G2-7joKmPk5vJKWxNMGQ/exec

{
  "name": "Tart",
  "timeStamp" : "2021-05-17T12:00:00"
}

###
GET http://localhost:8080/api/status9090/Tart/2024-9-24


###
GET http://localhost:8080/api/status9090/date
###
# GET https://script.google.com/macros/s/AKfycbzlgYf_yMU8CMUJYdi3DkpI9xx5gZk08QjB4wMfaOQxtalx-iracng1eXh9x52NNs-h_w/exec
# Content-Type: application/json

# {
#   "name": "tart"
# }


